# Generated by Django 3.2.4 on 2021-07-01 10:29

import Home.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Features',
            new_name='Input_Attributes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Model_Name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='x_values',
        ),
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Name', models.CharField(max_length=250)),
                ('Score', models.FloatField()),
                ('Features', Home.models.ListField()),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.project')),
            ],
        ),
    ]
