# Generated by Django 3.2.4 on 2021-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210702_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Learning',
            field=models.CharField(choices=[(1, 'Supervised'), (0, 'Unsupervised')], default=1, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='Type',
            field=models.CharField(choices=[(1, 'Classification'), (0, 'Regression')], default=0, max_length=250),
        ),
    ]
