# Generated by Django 3.2.4 on 2021-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210702_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Learning',
            field=models.CharField(choices=[('Supervised', 'Supervised'), ('Unsupervised', 'Unsupervised')], default=1, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='Type',
            field=models.CharField(choices=[('Classification', 'Classification'), ('Regression', 'Regression')], default=0, max_length=250),
        ),
    ]
